version: '3'
services:
  jd_scripts1:
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts1
    tty: true
    volumes:
      - ./logs1:/scripts/logs
    environment:
      - JD_COOKIE=pt_key=AAJftxrjADD9zqIP0V7pjDEkNpnTMVX6ZxRopB2avrIA69n81R0w37574iIlLEIbHWBav-n3yG4;pt_pin=993406467_m&pt_key=AAJfxMgoADBC4UVuCR7AZg3OIyeikLEy_dBDRID-qMRZchkXqg8UcAabzCCIqKAe2eUtbbUVbRE;pt_pin=jd_74d1b00658634;
      - CRONTAB_LIST_FILE=crontab_list.sh
      - PUSH_KEY=SCU69645T751603996ddcb96a66fe98a2087d89fb5dfaf35ad83fc
      - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
      - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
      - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
      - MARKET_COIN_TO_BEANS=20
      - MARKET_REWARD_NOTIFY=false
      - PET_NOTIFY_CONTROL=true
      - FRUIT_BEAN_CARD= true
      - JOY_FEED_COUNT=40
    command:
      - /bin/sh
      - -c
      - |
        git -C /scripts/ pull
        crond
        node
  jd_scripts2:
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts2
    tty: true
    volumes:
      - ./logs2:/scripts/logs
    environment:
      #姐姐
      - JD_COOKIE=pt_key=AAJf0c19ADCM4AgaPTJAy4LUZuq8RUAm7nnlPGrX6VmcLruYKjABW4kfzFZyQFKEhHUFsX0Wu2E;pt_pin=LemonCC1018&pt_key=AAJf0dSLADDvngPs1rjmc1kAeOvk42DX4MXWgaiNOuWDhL2KsSpiMdb5NS_gtJRO0oUiyuETZ78;pt_pin=ming121038673;
      - CRONTAB_LIST_FILE=crontab_list.sh
      - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
      - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
      - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
      - MARKET_COIN_TO_BEANS=20
      - MARKET_REWARD_NOTIFY=false
      - PET_NOTIFY_CONTROL=true
      - FRUIT_BEAN_CARD= true
      - JOY_FEED_COUNT=40
      - FACTORAY_WANTPRODUCT_NAME=投影仪
    command:
      - /bin/sh
      - -c
      - |
        git -C /scripts/ pull
        crond
        node
  jd_scripts3:
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts3
    tty: true
    volumes:
      - ./logs3:/scripts/logs
    environment:
      #胖墩&王硕&妈妈
      - JD_COOKIE=pt_key=AAJfw2rqADDpGGI0_NkClE3Qc1NSl_WIAno49dFk1jLcVvSWMOCORF2GojoHaghdSTdvwuFBxKo;pt_pin=jd_4ea9c773b942b&pt_key=AAJfvKQPADDz5iqn2r2hTkT2lAIvgLVXTTzQzoD2CSL7l2BbWsQhVDdKVu8_ekbbt-6S6xkh3YM;pt_pin=jd_4187a2b60c619&pt_key=AAJfyivnADDuUAC1y6OuLXYRaW5vC44ylGZ7MjV72MmVnTwVzU6OearSFXKEz3awRAkm6IQ3dNU;pt_pin=jd_wNNPtStaTdWX;
      - CRONTAB_LIST_FILE=crontab_list.sh
      - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
      - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
      - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
      - MARKET_COIN_TO_BEANS=20
      - MARKET_REWARD_NOTIFY=false
      - PET_NOTIFY_CONTROL=true
      - FRUIT_BEAN_CARD= true
      - JOY_FEED_COUNT=40
      - FACTORAY_WANTPRODUCT_NAME=投影仪
    command:
      - /bin/sh
      - -c
      - |
        git -C /scripts/ pull
        crond
        node
  jd_scripts4:
    image: akyakya/jd_scripts
    restart: always
    container_name: jd_scripts4
    tty: true
    volumes:
      - ./logs4:/scripts/logs
    environment:
    #小崔
      - JD_COOKIE=pt_key=AAJfzjRhADBDQFcLXEJu2bR3AeUb-PcW-zNN6twfNUdb4XsSh7WWpJzC3NZdhggo7RRgACzT_Aw;pt_pin=jd_490d7f4d4f8fd;
      - CRONTAB_LIST_FILE=crontab_list.sh
      - PUSH_KEY=SCU133435T439582d02149d89742cf459a9c8fed725fce37ad5aa1c
      - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
      - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
      - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
      - MARKET_COIN_TO_BEANS=20
      - MARKET_REWARD_NOTIFY=false
      - PET_NOTIFY_CONTROL=true
      - FRUIT_BEAN_CARD= true
      - JOY_FEED_COUNT=40
    command:
      - /bin/sh
      - -c
      - |
        git -C /scripts/ pull
        crond
        node