version: "3"
services:
  jd_scripts1: #我的&小费&小号
    image: zhangyujie666/jds
    restart: always
    container_name: jd_scripts1
    tty: true
    volumes:
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
      - ./src:/scripts/xiaoyu
      - ./logs1:/scripts/logs
    environment:
        #挂载自定义sh
      # - CUSTOM_SHELL_FILE=/scripts/xiaoyu/shell_script_mod.sh
      - JD_COOKIE=pt_key=AAJgBnwZADAdAlkguKXh2Y7ME2gUW_yfhTepI7a4l5CVKHTPrIjmVjaxymZOwfcQHcL1T3_at-I;pt_pin=993406467_m&pt_key=AAJgDpinADDHc66d9K4IvNkBhED7QZ8DqB_z3Dn66YBVig9GAzTFmZClWWgdox35SFtI3qPegb0;pt_pin=jd_74d1b00658634&pt_key=AAJf_m4DADBo1zFk5iu1XOQPxCEZcTmrDeeIOHpnrGMm6gndgO_MVHgUiq8b0CzWFnv5ljRSm9A;pt_pin=jd_HJvpwrDqLEqJ;
      - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
      - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
      - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
        #UA
      - JD_USER_AGENT=jdapp;iPhone;9.3.4;14.3;10302de0cff3d1d0d4b990d4cf729e2eac390594;network/4g;ADID/533BC320-CE01-4818-B7D7-9EF43517A1D0;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone12,1;addressid/3409494263;supportBestPay/0;appBuild/167502;jdSupportDarkMode/0;pv/345.28;apprpd/MyJD_Main;ref/MyJdMTAManager;psq/4;ads/;psn/10302de0cff3d1d0d4b990d4cf729e2eac390594|1112;jdv/0|iosapp|t_335139774|appshare|Wxfriends|1610496362812|1610496398;adk/;app_device/IOS;pap/JA2015_311210|9.3.4|IOS 14.3;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1
        #不执行的脚本
      - DO_NOT_RUN_SCRIPTS=jd_bj.js&jd_xxl_gh.js&jd_xxl.js&jd_gyec.js  
        #农场使用水滴换豆卡
      - FRUIT_BEAN_CARD= true
        #萌宠是否静默运行
      - PET_NOTIFY_CONTROL=true
        #宠汪汪喂食数量
      - JOY_FEED_COUNT=40
        #宠汪汪积分兑换多少京豆
      - JD_JOY_REWARD_NAME=20
        #东东工厂心仪商品
      - FACTORAY_WANTPRODUCT_NAME=投影仪
        #京小超兑换
      - MARKET_COIN_TO_BEANS=纯甄
        #签到结果简洁通知
      - JD_BEAN_SIGN_NOTIFY_SIMPLE=true
        #挂载自定义cron
      - CUSTOM_LIST_FILE=my_crontab_list.sh
        #东东工厂 不运行
      - JDFACTORY_FORBID_ACCOUNT=1&2
        #疯狂的joy开启循环助力
      - JDJOY_HELPSELF=true
        #疯狂的JOY购买等级
      - BUY_JOY_LEVEL=28
        #种豆得豆互助码
      - PLANT_BEAN_SHARECODES=e7lhibzb3zek2y4xvo5qo6ecx76bdxtlicbyxea@4oupleiwuds2a62vpwoiyyglj7iv65a62dz43wy&e7lhibzb3zek2y4xvo5qo6ecx76bdxtlicbyxea@4oupleiwuds2a62vpwoiyyglj7iv65a62dz43wy&e7lhibzb3zek2y4xvo5qo6ecx76bdxtlicbyxea@4oupleiwuds2a62vpwoiyyglj7iv65a62dz43wy
        #京喜工厂互助码
      - DREAM_FACTORY_SHARE_CODES=VUFcFE8mE-y7N_33EOWn3Q==@C-1-4msNcWJ7Gq4GO4Xq2w==@SHhVoR8WaIJEbFbS-rCz2w==&VUFcFE8mE-y7N_33EOWn3Q==@C-1-4msNcWJ7Gq4GO4Xq2w==@SHhVoR8WaIJEbFbS-rCz2w==&VUFcFE8mE-y7N_33EOWn3Q==@C-1-4msNcWJ7Gq4GO4Xq2w==@SHhVoR8WaIJEbFbS-rCz2w==
        #京东书店互助码
      - BOOKSHOP_SHARECODES=ba479feb9ed8416fb55aab76a82dd045
        #东东农场互助码
      - FRUITSHARECODES=76d3727f1c154d1baff411fbdf43fc94@8bf03a4fe64f4a32823e473a06d06fb8@8eb2ec97fe9d47f9a5a94ba7e32b2163&76d3727f1c154d1baff411fbdf43fc94@8bf03a4fe64f4a32823e473a06d06fb8@8eb2ec97fe9d47f9a5a94ba7e32b2163&76d3727f1c154d1baff411fbdf43fc94@8bf03a4fe64f4a32823e473a06d06fb8@8eb2ec97fe9d47f9a5a94ba7e32b2163
        #炸年兽互助码
      - JDNIAN_SHARECODES=cgxZdTXtIO-L413ODwb75rpMyO_31CBt-w2khYD2ISn8s2apIJOE9hsgDNw@cgxZdTXtY8SkikqqTFTNu9Mx2i0Egp8bAJOqOEkRWULsKfnYU7R7sKY&cgxZdTXtIO-L413ODwb75rpMyO_31CBt-w2khYD2ISn8s2apIJOE9hsgDNw@cgxZdTXtY8SkikqqTFTNu9Mx2i0Egp8bAJOqOEkRWULsKfnYU7R7sKY&cgxZdTXtIO-L413ODwb75rpMyO_31CBt-w2khYD2ISn8s2apIJOE9hsgDNw@cgxZdTXtY8SkikqqTFTNu9Mx2i0Egp8bAJOqOEkRWULsKfnYU7R7sKY
  jd_scripts2: #胖墩&王硕
    image: zhangyujie666/jds
    restart: always
    container_name: jd_scripts2
    tty: true
    volumes:
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
      - ./src:/scripts/xiaoyu
      - ./logs2:/scripts/logs
    environment:
        #挂载自定义sh
      # - CUSTOM_SHELL_FILE=/scripts/xiaoyu/shell_script_mod.sh
      - JD_COOKIE=pt_key=AAJgEtfaADCmERmBbU1l7TwAdItEkkQtr6CloNZssMYef2sBeB5BjM5RbBoCLNZZ9l-FV4BVAa0;pt_pin=jd_4ea9c773b942b&pt_key=AAJf-7w4ADA9pHw6GvWXfl-nM10YGmAxllZ3OGGhLHKdmhkpv9xZLgqpr4qGGfpNtLSXcdTBHSk;pt_pin=jd_wNNPtStaTdWX;
      - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
      - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
      - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
        #UA
      - JD_USER_AGENT=jdapp;iPhone;9.3.4;14.3;10302de0cff3d1d0d4b990d4cf729e2eac390594;network/4g;ADID/533BC320-CE01-4818-B7D7-9EF43517A1D0;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone12,1;addressid/3409494263;supportBestPay/0;appBuild/167502;jdSupportDarkMode/0;pv/345.28;apprpd/MyJD_Main;ref/MyJdMTAManager;psq/4;ads/;psn/10302de0cff3d1d0d4b990d4cf729e2eac390594|1112;jdv/0|iosapp|t_335139774|appshare|Wxfriends|1610496362812|1610496398;adk/;app_device/IOS;pap/JA2015_311210|9.3.4|IOS 14.3;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1
        #不执行的脚本
      - DO_NOT_RUN_SCRIPTS=jd_bj.js&jd_xxl_gh.js&jd_xxl.js&jd_gyec.js  
        #农场使用水滴换豆卡
      - FRUIT_BEAN_CARD= true
        #萌宠是否静默运行
      - PET_NOTIFY_CONTROL=true
        #宠汪汪喂食数量
      - JOY_FEED_COUNT=40
      - FACTORAY_WANTPRODUCT_NAME=投影仪
        #签到结果简洁通知
      - JD_BEAN_SIGN_NOTIFY_SIMPLE=true
        #挂载自定义cron
      - CUSTOM_LIST_FILE=my_crontab_list.sh
        #京喜工厂 不运行
      - DREAMFACTORY_FORBID_ACCOUNT=0
        #种豆得豆互助码
      - PLANT_BEAN_SHARECODES=b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy&b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy&b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy&b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy&b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy&b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy
      - DDFACTORY_SHARECODES=P04z54XCjVWnYaS5jwBC2T423hMkgs0@P04z54XCjVWnYaS5m9cZxiCmzwN1_z096HAMA@P04z54XCjVWnYaS5m9cZ2f8iX0YlZU5h5Nk2Dg&P04z54XCjVWnYaS5jwBC2T423hMkgs0@P04z54XCjVWnYaS5m9cZxiCmzwN1_z096HAMA@P04z54XCjVWnYaS5m9cZ2f8iX0YlZU5h5Nk2Dg
        #京喜工厂互助码
      - DREAM_FACTORY_SHARE_CODES=fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==&fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==&fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==&fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==&fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==&fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==
        #东东农场互助码
      - FRUITSHARECODES=13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94&13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94&13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94&13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94&13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94&13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94
        #疯狂的joy开启循环助力
      - JDJOY_HELPSELF=true
        #疯狂的JOY购买等级
      - BUY_JOY_LEVEL=28
      - JDJOY_SHARECODES=j4qNStBJlcSupeIHW6wjJQ==@I3LfPdCO9Q6lcEYaf7ZBy6t9zd5YaBeE@L0rVrwM-aQLYs6Knuo0wCw==
        #京东书店互助码
      - BOOKSHOP_SHARECODES=d5821ccb0f4f45138273bb9a1cd57392@6f7d8a3b889e4d99a05d8fd18497d0bb@69437be0d127472e8d6763595d283316&d5821ccb0f4f45138273bb9a1cd57392@6f7d8a3b889e4d99a05d8fd18497d0bb@69437be0d127472e8d6763595d283316&d5821ccb0f4f45138273bb9a1cd57392@6f7d8a3b889e4d99a05d8fd18497d0bb@69437be0d127472e8d6763595d283316&d5821ccb0f4f45138273bb9a1cd57392@6f7d8a3b889e4d99a05d8fd18497d0bb@69437be0d127472e8d6763595d283316&d5821ccb0f4f45138273bb9a1cd57392@6f7d8a3b889e4d99a05d8fd18497d0bb@69437be0d127472e8d6763595d283316&d5821ccb0f4f45138273bb9a1cd57392@6f7d8a3b889e4d99a05d8fd18497d0bb@69437be0d127472e8d6763595d283316
        #京喜农场互助码
      - JXNC_SHARECODES=2321b70af9f8eda7ad44715a73d37105@780da922dbc0bd092832bf9120200ec6@1b66d816285a9a9fe501e4070d43667a&2321b70af9f8eda7ad44715a73d37105@780da922dbc0bd092832bf9120200ec6@1b66d816285a9a9fe501e4070d43667a&2321b70af9f8eda7ad44715a73d37105@780da922dbc0bd092832bf9120200ec6@1b66d816285a9a9fe501e4070d43667a&2321b70af9f8eda7ad44715a73d37105@780da922dbc0bd092832bf9120200ec6@1b66d816285a9a9fe501e4070d43667a&2321b70af9f8eda7ad44715a73d37105@780da922dbc0bd092832bf9120200ec6@1b66d816285a9a9fe501e4070d43667a&2321b70af9f8eda7ad44715a73d37105@780da922dbc0bd092832bf9120200ec6@1b66d816285a9a9fe501e4070d43667a
        #炸年兽互助码
      - JDNIAN_SHARECODES=cgxZJmiBILrc7gjOZ1jlo-BDAwpTjzVPa2QNp6p3hTM@cgxZdTXtI76O61zJCAOs55j99nPHJ92nGg47LGZNQPXzirQ8s69E2E3kbfw@cgxZdTXtXMCcqkmLfETVmu5ORsUXuW7yztOpedf6V_qj5AF0-ZcNiyA&cgxZJmiBILrc7gjOZ1jlo-BDAwpTjzVPa2QNp6p3hTM@cgxZdTXtI76O61zJCAOs55j99nPHJ92nGg47LGZNQPXzirQ8s69E2E3kbfw@cgxZdTXtXMCcqkmLfETVmu5ORsUXuW7yztOpedf6V_qj5AF0-ZcNiyA&cgxZJmiBILrc7gjOZ1jlo-BDAwpTjzVPa2QNp6p3hTM@cgxZdTXtI76O61zJCAOs55j99nPHJ92nGg47LGZNQPXzirQ8s69E2E3kbfw@cgxZdTXtXMCcqkmLfETVmu5ORsUXuW7yztOpedf6V_qj5AF0-ZcNiyA&cgxZJmiBILrc7gjOZ1jlo-BDAwpTjzVPa2QNp6p3hTM@cgxZdTXtI76O61zJCAOs55j99nPHJ92nGg47LGZNQPXzirQ8s69E2E3kbfw@cgxZdTXtXMCcqkmLfETVmu5ORsUXuW7yztOpedf6V_qj5AF0-ZcNiyA&cgxZJmiBILrc7gjOZ1jlo-BDAwpTjzVPa2QNp6p3hTM@cgxZdTXtI76O61zJCAOs55j99nPHJ92nGg47LGZNQPXzirQ8s69E2E3kbfw@cgxZdTXtXMCcqkmLfETVmu5ORsUXuW7yztOpedf6V_qj5AF0-ZcNiyA&cgxZJmiBILrc7gjOZ1jlo-BDAwpTjzVPa2QNp6p3hTM@cgxZdTXtI76O61zJCAOs55j99nPHJ92nGg47LGZNQPXzirQ8s69E2E3kbfw@cgxZdTXtXMCcqkmLfETVmu5ORsUXuW7yztOpedf6V_qj5AF0-ZcNiyA
  # jd_scripts3:
  #   image: akyakya/jd_scripts
  #   restart: always
  #   container_name: jd_scripts3
  #   tty: true
  #   volumes:
  #     - ./logs3:/scripts/logs
  #   environment:
  #     - JD_COOKIE=pt_key=AAJfzjRhADBDQFcLXEJu2bR3AeUb-PcW-zNN6twfNUdb4XsSh7WWpJzC3NZdhggo7RRgACzT_Aw;pt_pin=jd_490d7f4d4f8fd;
  #     - DD_BOT_TOKEN=3d604445f0bbbb129185d0d244a218407f23630905276cb06eb0774fe012c689
  #     - DD_BOT_SECRET=SEC93c1887a89a0af24e25e1a742fc108fceeacaa0254fc158c50c3c1cc7bdfb362
  #     - UN_SUBSCRIBES=100&100&iPhone12&Apple京东自营旗舰店
  #     - FRUIT_BEAN_CARD= true
  #       #萌宠是否静默运行
  #     - PET_NOTIFY_CONTROL=true
  #     - JOY_FEED_COUNT=40
  #     - FACTORAY_WANTPRODUCT_NAME=投影仪
  #     - JD_BEAN_SIGN_NOTIFY_SIMPLE=true
  #     - CUSTOM_LIST_FILE=my_crontab_list.sh
  #     - JDJOY_HELPSELF=true
  #     - JDJOY_SHARECODES=j4qNStBJlcSupeIHW6wjJQ==@I3LfPdCO9Q6lcEYaf7ZBy6t9zd5YaBeE@L0rVrwM-aQLYs6Knuo0wCw==
  #     - PLANT_BEAN_SHARECODES=b6xxkujlkjykfriicy7emnyhbm@x3x7xhsua3bmimhz52vugklnh44xq65ksalcx7a@4npkonnsy7xi2mbgrx7s7k4kc5ibhk5m7ifbjyy
  #     - DDFACTORY_SHARECODES=P04z54XCjVWnYaS5jwBC2T423hMkgs0@P04z54XCjVWnYaS5m9cZxiCmzwN1_z096HAMA@P04z54XCjVWnYaS5m9cZ2f8iX0YlZU5h5Nk2Dg&P04z54XCjVWnYaS5jwBC2T423hMkgs0@P04z54XCjVWnYaS5m9cZxiCmzwN1_z096HAMA@P04z54XCjVWnYaS5m9cZ2f8iX0YlZU5h5Nk2Dg&P04z54XCjVWnYaS5jwBC2T423hMkgs0@P04z54XCjVWnYaS5m9cZxiCmzwN1_z096HAMA@P04z54XCjVWnYaS5m9cZ2f8iX0YlZU5h5Nk2Dg
  #     - FRUITSHARECODES=13cd7d9990544ca29195aee9d2574395@e436bdfeaa454902ad20fddd1ce096b5@3c7658fedf724c929c9d924c433f70ae@76d3727f1c154d1baff411fbdf43fc94
  #     - DREAM_FACTORY_SHARE_CODES=fhEyWnDSm2PmfOajBltZWg==@07HXmMgtDo7VQFSb8oxXxA==@vmlNjZVbTsZ2lzeFh3tHYA==
