let a = {
  id: "iboxpay",
  name: "笑谱",
  keys: [
    "iboxpayheader",
    "iboxpayheader2",
    "iboxpayheader3",
    "iboxpayheader4",
    "iboxpayheader5",
    "iboxpayheader6",
    "iboxpayheader7",
    "iboxpayheader8",
    "iboxpayheader9",
    "iboxpayheader10",
    "iboxpayheader11",
    "iboxpayheader12",
    "iboxpayheader13",
    "iboxpayheader14",
    "iboxpayheader15",
    "iboxpayheader16",
    "iboxpayheader17",
    "iboxpayheader18",
    "iboxpayheader19",
    "iboxpayheader20",
  ],
  author: "@ziye",
  settings: [
    {
      id: "iboxpaySuffix",
      name: "当前账号",
      val: "1",
      type: "number",
      desc: "当前抓取ck记录的账号序号，如：1、2、4、",
    },
    {
      id: "iboxpayCount",
      name: "账号个数",
      val: "1",
      type: "number",
      desc: "指定任务最多跑几个账号，根据抓取的账号数据个数来设值",
    },
    {
      id: "iboxpayCASH",
      name: "提现标准",
      val: "0",
      type: "number",
      desc: "0不提现，可设置 0 1 15 30 100  ",
    },
  ],
  repo:
    "https://raw.githubusercontent.com/ziye12/JavaScript/main/Task/iboxpay.js",
  icons: [
    "https://raw.githubusercontent.com/ziye12/JavaScript/main/Task/iboxpay.png",
    "https://raw.githubusercontent.com/ziye12/JavaScript/main/Task/iboxpay.png",
  ],
  script:
    "https://raw.githubusercontent.com/ziye12/JavaScript/main/Task/iboxpay.js",
  icon:
    "https://raw.githubusercontent.com/ziye12/JavaScript/main/Task/iboxpay.png",
  favIcon: "mdi-star-outline",
  favIconColor: "grey",
  datas: [
    {
      key: "iboxpayheader",
      val:
        '',
    },
    { key: "iboxpayheader2", val: "" },
    { key: "iboxpayheader3", val: "" },
    { key: "iboxpayheader4", val: "" },
    { key: "iboxpayheader5", val: "" },
    { key: "iboxpayheader6", val: "" },
    { key: "iboxpayheader7", val: "" },
    { key: "iboxpayheader8", val: "" },
    { key: "iboxpayheader9", val: "" },
    { key: "iboxpayheader10", val: "" },
    { key: "iboxpayheader11", val: "" },
    { key: "iboxpayheader12", val: "" },
    { key: "iboxpayheader13", val: "" },
    { key: "iboxpayheader14", val: "" },
    { key: "iboxpayheader15", val: "" },
    { key: "iboxpayheader16", val: "" },
    { key: "iboxpayheader17", val: "" },
    { key: "iboxpayheader18", val: "" },
    { key: "iboxpayheader19", val: "" },
    { key: "iboxpayheader20", val: "" },
  ],
  sessions: [],
  isLoaded: true,
};
