let a = {
  fqkkurl: "http://m.chuangyitech.top/reada/getTask",
  fqkkhd:
    '{"Accept":"*/*","Accept-Encoding":"gzip, deflate","Origin":"http://m.chuangyitech.top","Cookie":"autoRead=1; udtauth=e030PDk0rTmw9SEUAcni5zQvorHa2Y8CF2rF0A%2FPfEqU8uHVTAuEJNsCyxzGqEw9lpt2YJqhiyX7dGH6ldvEyuYm7jP%2BE1GST5TeOeOIsvs34ujcAMMlDI9YXWKp1Lcs6XrWUCBRBggiEAcgEIOVXzp8Mupc1QkwULGhHFU0GTg; PHPSESSID=ia9une5qkaj07eoo7tq17rpsf4","Connection":"keep-alive","Host":"m.chuangyitech.top","Content-Length":"0","User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.2(0x1800022e) NetType/WIFI Language/zh_CN","Referer":"http://m.chuangyitech.top/reada/","Accept-Language":"zh-cn","X-Requested-With":"XMLHttpRequest"}',
  fqkkurl2: "",
  fqkkhd2: "",
  fqkkurl3: "",
  fqkkhd3: "",
  fqkkurl4: "",
  fqkkhd4: "",
  fqkkurl5: "",
  fqkkhd5: "",
  fqkkurl6: "",
  fqkkhd6: "",
  fqkkurl7: "",
  fqkkhd7: "",
  fqkkurl8: "",
  fqkkhd8: "",
  fqkkurl9: "",
  fqkkhd9: "",
  fqkkurl10: "",
  fqkkhd10: "",
  fqkkurl11: "",
  fqkkhd11: "",
  fqkkurl12: "",
  fqkkhd12: "",
  fqkkurl13: "",
  fqkkhd13: "",
  fqkkurl14: "",
  fqkkhd14: "",
  fqkkurl15: "",
  fqkkhd15: "",
};

console.log(JSON.stringify(a));
